## Project Configuration
#platform :ios, "9.0"
project 'ImHungryiOS'

## Settings
use_frameworks!
inhibit_all_warnings!

target 'ImHungryiOS' do
 ## Pods
 ## - Networks
 pod 'Alamofire', '~> 4.5'
 ## - Parsing, Encoding, Decoding
 pod 'SwiftyJSON'
 ## - UI Components
 pod 'Kingfisher', '~> 4.0'
 
 target 'ImHungryiOSTests' do
  inherit! :search_paths
 end

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
      puts target.name
      
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.0'
      end
    end
end